// <auto-generated />
using System;
using NascentiaFlow.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NascentiaFlow.Migrations.Edition
{
    [DbContext(typeof(EditionContext))]
    partial class EditionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("EgoPrimer.Entities.Edition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EditionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EditionTimestamp")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Format")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Editions");
                });
#pragma warning restore 612, 618
        }
    }
}
